# Generated by Django 5.0.2 on 2024-02-13 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_ods_club_ods_licence_delete_ods_player'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Player',
        ),
    ]
