# Generated by Django 5.0.2 on 2024-02-14 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_delete_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='D_Age_Group',
            fields=[
                ('code', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='D_Club_Type',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='D_Date',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='D_Federation',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='D_Geography',
            fields=[
                ('code', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('code_commune', models.CharField(max_length=5)),
                ('commune', models.CharField(max_length=150)),
                ('code_qpv', models.CharField(max_length=8)),
                ('qpv', models.CharField(max_length=150)),
                ('code_departement', models.CharField(max_length=3)),
                ('departement', models.CharField(max_length=150)),
                ('region', models.CharField(max_length=100)),
                ('statut', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='D_Sexe',
            fields=[
                ('code', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='F_Club',
            fields=[
                ('code', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nombre', models.IntegerField()),
                ('club_type_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.d_club_type')),
                ('date_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.d_date')),
                ('federation_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.d_federation')),
                ('geography_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.d_geography')),
            ],
        ),
        migrations.CreateModel(
            name='F_Licence',
            fields=[
                ('code', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('nombre', models.IntegerField()),
                ('age_group_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.d_age_group')),
                ('date_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.d_date')),
                ('federation_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.d_federation')),
                ('geography_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.d_geography')),
                ('sexe_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.d_sexe')),
            ],
        ),
    ]
